alter session set "_ORACLE_SCRIPT"=true;

CREATE TABLE Empleados (
Nombre VARCHAR(30) CONSTRAINT NOMBRE_NT NOT NULL,
DNI VARCHAR(9) CONSTRAINT DNI_PK PRIMARY KEY,
Sexo CHAR(1) CONSTRAINT SEXO_CHECK CHECK (SEXO = 'M' OR SEXO = 'F'),
Categoria NUMBER(2),
Anyos NUMBER(3) CONSTRAINT ANYOS_CHECK CHECK (ANYOS >=0),
Sueldo NUMBER,
CONSTRAINT CATEGORIA_FK FOREIGN KEY (Categoria) REFERENCES Nominas(Categoria)
);

CREATE TABLE Nominas (
Categoria NUMBER(2) CONSTRAINT CATEGORIA_CHECK CHECK (CATEGORIA >=1 AND CATEGORIA <=10) CONSTRAINT CATEGORIA_PK PRIMARY KEY, 
Sueldo_Base NUMBER CONSTRAINT CURSO_NT NOT NULL
);


INSERT INTO Nominas VALUES (1, 50000);
INSERT INTO Nominas VALUES (2, 70000);
INSERT INTO Nominas VALUES (3, 90000);
INSERT INTO Nominas VALUES (4, 110000);
INSERT INTO Nominas VALUES (5, 130000);
INSERT INTO Nominas VALUES (6, 150000);
INSERT INTO Nominas VALUES (7, 170000);
INSERT INTO Nominas VALUES (8, 190000);
INSERT INTO Nominas VALUES (9, 210000);
INSERT INTO Nominas VALUES (10, 230000);

INSERT INTO Empleados VALUES ('James Cosling', '32000032G', 'M', 4, 7, 145000);
INSERT INTO Empleados VALUES ('Ada Lovelace', '32000031R', 'F', 1, 9, 95000);


